[build-system]
build-backend = "scikit_build_core.build"
requires = [
  "scikit-build-core>=0.9",
  "pybind11>=2.12",        # ensures Python + CMake integration
  "setuptools>=68",
]

[project]
name = "pyle"
version = "0.1.0"
description = "Python bindings for a Lean 4 interpreter"
readme = "README.md"
authors = [
    { name = "Nilay Patel", email = "nilaypatel2@gmail.com" },
]
requires-python = ">=3.8"
license = { text = "MIT" }

[project.urls]
Homepage = "https://github.com/yourusername/pyle"
Repository = "https://github.com/yourusername/pyle"

[tool.scikit-build]
minimum-version = "0.9"
wheel.expand-macos-universal-tags = true
wheel.install-dir = "."

[tool.scikit-build.cmake]
source-dir = "."
build-type = "Release"

[tool.rye]
dev-dependencies = [
    "pytest>=8.4.2",
    "ipython>=9.6.0",
]

[tool.cibuildwheel]
xbuild-tools = ["cmake", "/Users/offendo/.elan/bin/lake"]
build-verbosity = 3
before-all = [
  "curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:${LEAN_VERSION}",
  "~/.elan/bin/elan toolchain install leanprover/lean4:${LEAN_VERSION}"
  ]
environment= { LEAN_VERSION = "v4.24.0", PATH="$PATH:$HOME/.elan/bin" }
