[build-system]
build-backend = "scikit_build_core.build"
requires = [
  "scikit-build-core>=0.9",
  "pybind11>=2.12",        # ensures Python + CMake integration
  "setuptools>=68",
]

[project]
name = "pyle"
version = "0.1.0"
description = "Python bindings for a Lean 4 interpreter"
readme = "README.md"
authors = [
    { name = "Nilay Patel", email = "nilaypatel2@gmail.com" },
]
requires-python = ">=3.8"
license = { text = "MIT" }

[project.urls]
Homepage = "https://github.com/offendo/pyle"
Repository = "https://github.com/offendo/pyle"

[tool.scikit-build]
minimum-version = "0.9"
wheel.expand-macos-universal-tags = true
wheel.install-dir = "."

[tool.scikit-build.cmake]
source-dir = "."
build-type = "Release"

[tool.rye]
dev-dependencies = [
    "pytest>=8.4.2",
    "ipython>=9.6.0",
    "datasets>=4.4.1",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
    "cppclean>=0.13",
]
